apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-pv005
  labels:
    name: nfs-pv005
spec: 
  nfs:
    path: /data/nfs/volumes/v5
    server: 192.168.9.242
  accessModes: ['ReadWriteOnce', 'ReadWriteMany', 'ReadOnlyMany']
  capacity:
    storage: 100Gi
