apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-pv003
  labels:
    name: nfs-pv003
spec: 
  nfs:
    path: /data/nfs/volumes/v3
    server: 192.168.9.242
  accessModes: ['ReadWriteOnce', 'ReadWriteMany', 'ReadOnlyMany']
  capacity:
    storage: 100Gi
