apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-pv004
  labels:
    name: nfs-pv004
spec: 
  nfs:
    path: /data/nfs/volumes/v4
    server: 192.168.9.242
  accessModes: ['ReadWriteOnce', 'ReadWriteMany', 'ReadOnlyMany']
  capacity:
    storage: 100Gi
