apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-pv001
  labels:
    name: nfs-pv001
spec: 
  nfs:
    path: /data/nfs/volumes/v1
    server: 192.168.9.242
  accessModes: ['ReadWriteOnce', 'ReadWriteMany', 'ReadOnlyMany']
  capacity:
    storage: 20Gi
