apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api.xxx.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - api.xxx.com
    secretName: xxx.com
  rules:
  - host: api.xxx.com
    http:
      paths:
      - path: /(tjkcms|tjkmessage|tjkuser|tjkproduct|tjkhouse|tjkmobile)
        backend:
          serviceName: tuanjuker-gateway
          servicePort: 8888
