apiVersion: v1
kind: Service
metadata:
  name: wayne-frontend-lb
  annotations:
    metallb.universe.tf/address-pool: default # 前面config中声明的地址池
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wayne-frontend
  type: LoadBalancer
