apiVersion: v1
kind: Service
metadata:
  name: house-mysql
  labels:
    name: house-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30060
      protocol: TCP
  selector:
     app: house-mysql
